/// Predicted-vs-actual churn rate per probability decile, for the calibration plot.
table Calibration
	lineageTag: d1cca453-bb82-4789-9f55-b57c5ca43831

	column bucket_label
		dataType: string
		lineageTag: 9c2906c5-b1cb-4439-be9b-c9d1ea698efe
		summarizeBy: none
		sourceColumn: bucket_label
		sortByColumn: bucket_order

		annotation SummarizationSetBy = Automatic

	column predicted_avg
		dataType: double
		formatString: 0.0%
		lineageTag: 3c5e733b-931a-429f-ba69-247a0b85f09b
		summarizeBy: none
		sourceColumn: predicted_avg

		annotation SummarizationSetBy = Automatic

	column actual_rate
		dataType: double
		formatString: 0.0%
		lineageTag: 9d9a481b-38b5-4a67-82d7-1408fce5d43c
		summarizeBy: none
		sourceColumn: actual_rate

		annotation SummarizationSetBy = Automatic

	column customer_count
		dataType: int64
		lineageTag: 7e58f7e9-d750-4b1e-96db-f336e0e7b9a4
		summarizeBy: sum
		sourceColumn: customer_count

		annotation SummarizationSetBy = Automatic

	column bucket_order
		dataType: int64
		isHidden
		lineageTag: 6ec4f9d2-f4dd-43fc-9bfc-be8e5a00ce2a
		summarizeBy: none
		sourceColumn: bucket_order

		annotation SummarizationSetBy = Automatic

	partition Calibration = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolderPath & "calibration.csv"), [Delimiter=",", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"bucket_label", type text}, {"predicted_avg", type number}, {"actual_rate", type number}, {"customer_count", Int64.Type}, {"bucket_order", Int64.Type}})
				in
				    #"Changed Type"
